fmidev/weather-app

.eslintrc.js
package.json
src/store/forecast/actions.ts
src/store/forecast/reducer.ts
src/store/forecast/types.ts
src/store/index.ts
src/store/settings/actions.ts
src/store/settings/reducer.ts
src/store/settings/types.ts
src/utils/async_storage.ts
yarn.lock

Initialized reducers (selectors still missing). Changed eslint to lint typescript files (`.ts`, `.tsx`).

initialize reducers

---

src/store/forecast/selectors.ts
src/store/settings/selectors.ts
src/store/types.ts

Added simple selectors for current state

add selectors for reducers

---

.env.default
.eslintrc.js
README.md
__tests__/store/settings.test.ts
i18n/en.json
i18n/fi.json
package.json
src/navigators/TabNavigator.tsx
src/screens/SettingsScreen.tsx
src/store/settings/actions.ts
src/store/settings/reducer.ts
src/store/settings/selectors.ts
src/store/settings/types.ts
src/utils/async_storage.ts
src/utils/units.ts
yarn.lock

Added units. Units are defined in `.env` (see README.md).
Requires `yarn install`.

add modular units

---

.detoxrc.json
e2e/config.json
e2e/init.ts
e2e/navigation.test.ts
e2e/settings.test.ts
src/screens/SettingsScreen.tsx

Fixing detox for iOS will follow in next pull request.

settings e2e tests

---

src/navigators/TabNavigator.tsx

add android StatusBar styling

---

src/components/ForecastPanel.tsx

Allow multiple days to be open. Move TouchableOpacity to entire row.

change ForecastPanel opening functionality

---

src/components/ObservationPanel.tsx
src/network/WeatherApi.ts
src/screens/WeatherScreen.tsx
src/store/index.ts
src/store/observation/actions.ts
src/store/observation/reducer.ts
src/store/observation/selector.ts
src/store/observation/types.ts
src/store/types.ts

Observation handlers & simple component to test logic.

Observation data handlers & base for component

---

i18n/en.json
i18n/fi.json
package.json
src/assets/images/icons/wind-arrow.svg
src/components/CollapsibleChartList.tsx
src/components/DaySelectorWrapper.tsx
src/components/ForecastPanel.tsx
src/components/Icon.tsx
src/components/PrecipitationBarChart.tsx
src/components/TemperatureLineChart.tsx
src/components/WindLineChart.tsx
src/navigators/themes.ts
src/network/WeatherApi.ts
src/store/forecast/types.ts
src/utils/chartTheme.ts
src/utils/colors.ts
yarn.lock

First implementation of forecast charts.
Requires `yarn install`.

add implementation of victory-native charts

---

__tests__/store/location.test.ts
src/store/location/actions.ts
src/store/location/reducer.ts
src/store/location/types.ts

Move use of Config from reducer to actions to fix app not opening.

use config from actions instead of reducer

---

index.js

Disables font scaling for MVP purposes.

disable font scaling from Text and TextInput by default

---

package.json
src/components/weather/ForecastPanel.tsx
src/components/weather/ObservationPanel.tsx
src/components/weather/forecast/PrecipitationStrip.tsx
src/config/types.ts
src/navigators/Types.ts
src/network/WeatherApi.ts
src/store/forecast/actions.ts
src/store/forecast/types.ts
src/store/location/selector.ts
src/store/location/types.ts
src/store/observation/actions.ts
src/store/observation/types.ts
src/utils/helpers.ts
yarn.lock

- Use location timezone to display time
- Multi producer support for observations

Time and location improvements

---

src/components/weather/ForecastPanel.tsx
src/components/weather/charts/ParameterSelector.tsx
src/components/weather/forecast/ForecastByHourList.tsx

A bunch of style related refactorings (added LinearGradient) to both `ParameterSelector` and `ForecastByHourList`.

add missing styles to ForecastByHourList refactor Parameter selector

---

__tests__/config/provider.test.tsx
src/components/weather/ObservationPanel.tsx
src/config/ConfigProvider.tsx
src/config/types.ts
src/screens/WarningsScreen.tsx
src/screens/WeatherScreen.tsx
src/utils/reloader.ts

Uses DynamicConfig to tell other comoponents when application is brought to active state and configs are updated if needed.
Requires `updateInterval` parameters to be set in `defaultConfig`: weather.forecast, weather.observation & warnings

Automatically reload data

---

src/components/map/ui/TimeSlider.tsx

Refactor timeslider logic.
Closes #94

adjust timeslider

---

src/components/weather/charts/TimeSelector.tsx

Style according to new design (Zeplin 5.6).

change chart TimeSelector styling

---

i18n/en.json
i18n/fi.json
src/components/weather/ObservationPanel.tsx
src/components/weather/common/CollapsibleHeader.tsx
src/components/weather/common/ParameterSelector.tsx
src/components/weather/forecast/ChartList.tsx
src/components/weather/sheets/ObservationStationListBottomSheet.tsx
src/store/observation/selector.ts

- Styling fixes on ObservationPanel
- Store chart/list selection
- BottomSheet styling

Small tweaks & style changes

---

src/config/types.ts
src/store/map/types.ts
src/utils/map.ts

`defaultconfig.ts`
```ts
...
customParameters: {
'l1.attributes.opacity': 0.8,
},
...
```

Add customParameters to layers

---

i18n/en.json
i18n/fi.json
src/components/map/sheets/InfoBottomSheet.tsx
src/components/map/ui/TimeSlider.tsx
src/components/weather/ForecastPanel.tsx
src/components/weather/ObservationPanel.tsx
src/components/weather/common/CollapsibleHeader.tsx
src/navigators/themes.ts
src/utils/colors.ts

- Kartan infoliukuri
- Aikasliderin tyylit
- Lista/taulukko/graafi nappuloiden tyylittely
- Havainto valitsimeen ikoni

remaining style and content fixes for mvp

---

android/app/build.gradle
ios/MobileWeatherDev.xcodeproj/project.pbxproj
ios/MobileWeatherDev/Info.plist
package.json
src/components/weather/ForecastPanel.tsx
src/components/weather/charts/Chart.tsx
src/components/weather/forecast/ChartList.tsx
src/components/weather/forecast/ForecastByHourList.tsx
src/components/weather/forecast/ForecastListColumn.tsx
src/components/weather/forecast/ForecastListHeaderColumn.tsx
src/store/forecast/selectors.ts

missing: styling (`LinearGradient`)

use day strip for list and chart

---

src/components/weather/forecast/ForecastByHourList.tsx

fix day duration row day

---

src/components/weather/GradientWrapper.tsx
src/screens/WeatherScreen.tsx
src/utils/colors.ts

Adds a gradient background to WeatherScreen based on `nextHourForecast.temperature`. Only applicable to light theme.

add GradientWrapper

---

__tests__/store/map.test.ts
src/components/map/layers/WMSOverlay.tsx
src/components/map/sheets/MapLayersBottomSheet.tsx
src/components/map/ui/TimeSlider.tsx
src/store/map/actions.ts
src/store/map/reducer.ts
src/store/map/selectors.ts
src/store/map/types.ts
src/utils/map.ts

* Fix initial timestep selection
* Add ActivityIndicator 
closes #158

Fix timeSlider initial timeStep

---

src/navigators/TabNavigator.tsx
src/screens/SearchScreen.tsx

navigate back from search screen on tab press

---

__tests__/store/location.test.ts
src/components/search/AreaList.tsx
src/store/location/actions.ts
src/store/location/reducer.ts
src/store/location/selector.ts
src/store/location/types.ts

Add geolocation to recent list
Only show it while geolocation is selected
closes #176

Add geolocation to recent list

---

ios/Podfile.lock
package.json
src/components/map/ui/TimeSlider.tsx
yarn.lock

Add hapticFeedback on step change
closes #178

Add hapticFeedback on step change

---

src/components/warnings/WarningsWebViewPanel.tsx

Use self generated html to easily manage variants.

Warnings webview support for darkmode

---

i18n/en.json
i18n/fi.json
src/components/weather/charts/Chart.tsx
src/components/weather/charts/ChartDataRenderer.tsx
src/components/weather/charts/ChartYAxis.tsx
src/components/weather/charts/CloudHeightChart.tsx
src/components/weather/charts/HumidityChart.tsx
src/components/weather/charts/Legend.tsx
src/components/weather/charts/PrecipitationChart.tsx
src/components/weather/charts/PressureChart.tsx
src/components/weather/charts/TemperatureChart.tsx
src/components/weather/charts/UvChart.tsx
src/components/weather/charts/VisCloudChart.tsx
src/components/weather/charts/WindChart.tsx
src/components/weather/charts/settings.ts
src/components/weather/charts/types.ts
src/components/weather/forecast/ChartList.tsx
src/components/weather/observation/List.tsx
src/utils/chart.ts
src/utils/chartTheme.ts

* Add missing charts
* Refactor yAxises
* Fix double yAxis charts
* Fix styles
closes #181

chart fixes

---

__tests__/store/location.test.ts
src/network/AutocompleteApi.ts
src/network/WeatherApi.ts
src/screens/SettingsScreen.tsx
src/store/location/actions.ts
src/store/location/reducer.ts
src/store/location/selector.ts
src/store/location/types.ts
src/utils/helpers.ts

* Fix location locales when changin language
* Fix location area when using geolocation in Finland
** timeseries region !== autocomplete area
closes #190

Fix location locales

---

src/navigators/TabNavigator.tsx
src/store/navigation/reducer.ts

Change default tab to Weather

---

src/components/map/ui/TimeSlider.tsx

* Use different methdod per OS
Closes #195

Change hapticFeedback methods

---

src/components/map/layers/TimeseriesMarker.tsx
src/components/weather/NextHourForecastPanel.tsx
src/components/weather/forecast/DaySelectorList.tsx
src/components/weather/forecast/ForecastListColumn.tsx

Fix celsius units

---

src/components/weather/forecast/ForecastByHourList.tsx

* Fix dayDuration row to fit in
* Also works with scaling fonts now
closes #200

Fix dayDuration row layout

---

__tests__/store/map.test.ts
src/components/map/layers/TimeseriesMarker.tsx
src/screens/MapScreen.tsx
src/store/map/actions.ts
src/store/map/reducer.ts
src/store/map/selectors.ts
src/store/map/types.ts

One callout open at a time

---

src/components/weather/NextHourForecastPanel.tsx
src/components/weather/forecast/ForecastByHourList.tsx
src/components/weather/forecast/ForecastListColumn.tsx
src/network/WeatherApi.ts

- Highlight day change
- Windspeed layout
- Fix query return times and remove unused param
- Change day start to 00:00 & fix dayIndex math

Random fixes

---

i18n/en.json
i18n/fi.json
src/navigators/TabNavigator.tsx
src/navigators/Types.ts
src/screens/OnboardingScreen.tsx
src/screens/SetupScreen.tsx
src/utils/colors.ts

add onboarding flow

---

__tests__/store/forecast.test.ts
src/components/warnings/WarningsPanel.tsx
src/components/warnings/WarningsPanelSlim.tsx
src/components/weather/ForecastPanel.tsx
src/components/weather/common/PanelHeader.tsx
src/config/types.ts
src/store/forecast/reducer.ts
src/store/forecast/selectors.ts
src/store/forecast/types.ts
src/store/warnings/reducer.ts
src/store/warnings/selectors.ts
src/store/warnings/types.ts

Add data age warnings

---

i18n/en.json
i18n/fi.json
src/components/map/sheets/InfoBottomSheet.tsx
src/components/map/sheets/MapLayersBottomSheet.tsx

changes to map bottom sheets

---

src/network/WarningsApi.ts
src/store/warnings/actions.ts

Warnings api structure update

---

__tests__/store/forecast.test.ts
src/store/forecast/actions.ts
src/store/forecast/reducer.ts
src/store/forecast/selectors.ts
src/store/forecast/types.ts

Fixed parameter order

---

__tests__/store/map.test.ts
src/components/map/layers/WMSOverlay.tsx
src/components/map/sheets/InfoBottomSheet.tsx
src/components/weather/charts/Legend.tsx
src/components/weather/charts/PrecipitationChart.tsx
src/components/weather/forecast/PrecipitationStrip.tsx
src/components/weather/sheets/WeatherInfoBottomSheet.tsx
src/config/types.ts
src/navigators/themes.ts
src/store/map/types.ts
src/utils/colors.ts
src/utils/helpers.ts
src/utils/map.ts

Add dark/light precipitation

---

__tests__/store/map.test.ts
i18n/en.json
i18n/fi.json
ios/Podfile.lock
package.json
src/components/common/ErrorComponent.tsx
src/navigators/TabNavigator.tsx
src/store/forecast/reducer.ts
src/store/map/actions.ts
src/store/map/reducer.ts
src/store/map/selectors.ts
src/store/map/types.ts
src/store/observation/reducer.ts
src/store/warnings/reducer.ts
yarn.lock

add ErrorComponent

---

src/components/map/ui/TimeSlider.tsx

To reproduce (from `main`): 
1) toggle animation
2) change map layer

clear animation on map layer change

---

src/store/warnings/selectors.ts

Fix warnings day handling

---

src/components/weather/NextHourForecastPanel.tsx
src/components/weather/forecast/ForecastByHourList.tsx

Fix sunset & sunrise time handling

---

src/components/common/CommonHeaderTitle.tsx
src/components/common/ErrorComponent.tsx
src/components/weather/NextHourForecastPanel.tsx

minor style adjustments

---

android/app/src/main/AndroidManifest.xml

fix android manifest

---

src/config/types.ts
src/screens/MapScreen.tsx
src/store/map/selectors.ts

Fix initial overlay loading

---

src/assets/images/icons/warnings-flooding-orange.svg
src/assets/images/icons/warnings-flooding-red.svg
src/components/warnings/DayDetails.tsx

Warning color fixes

---

src/components/weather/charts/Legend.tsx
src/components/weather/sheets/WeatherInfoBottomSheet.tsx
src/utils/colors.ts
src/utils/helpers.ts

Update precipitation limits & colors

---

src/utils/map.ts

Filter smartmet-server getCapabilities with namespace
closes #262

getCapabilities namespace filter

---

src/components/weather/observation/List.tsx
src/utils/helpers.ts

ObservationList layout changes

---

src/screens/FeedbackScreen.tsx

Add info about device to feedback

---

i18n/en.json
i18n/fi.json
src/components/weather/ObservationPanel.tsx

No available observations handling

---

src/components/map/layers/WMSOverlay.tsx
src/components/warnings/DayDetails.tsx
src/components/warnings/WarningsWebViewPanel.tsx
src/components/weather/common/PanelHeader.tsx
src/components/weather/observation/List.tsx
src/network/AutocompleteApi.ts
src/network/WarningsApi.ts
src/network/WeatherApi.ts
src/store/warnings/selectors.ts
src/utils/map.ts

- Add who indicator to queries
- Fix warnings overflow, key & undefined severities
- Fix PanelHeader text in bigger font scaling
- Fix day change in observationList

Various fixes

---

src/components/map/layers/TimeseriesOverlay.tsx

- Redcuce unnecessary data manipulation
- Prioritize bigger population in cluster calculation start points
- Change clustering radius & extent

TimeseriesOverlay improvements

---

i18n/en.json
i18n/fi.json
src/screens/SearchScreen.tsx

implement remaining accessibility features

---

src/screens/OnboardingScreen.tsx
src/screens/SetupScreen.tsx

fix onboarding flow font scalability

---

src/navigators/TabNavigator.tsx
src/store/location/reducer.ts

prevent locate on language change

---

src/config/types.ts
src/utils/map.ts

enable custom image ratio for wms overlays

---

src/utils/helpers.ts

only temperature values can have minus

---

src/screens/MapScreen.tsx

map min and max zoom values

---

i18n/en.json
i18n/fi.json
i18n/sv.json
ios/Podfile.lock
src/components/warnings/WarningsSymbol.tsx
src/store/warnings/constants.ts

fix thunderstorm warning not showing, update pods to match package.json

---

src/components/announcements/CrisisStrip.tsx
src/components/common/AccessibleTouchableOpacity.tsx
src/components/warnings/WarningsPanel.tsx
src/components/warnings/WarningsPanelSlim.tsx
src/components/warnings/WarningsWebViewPanel.tsx
src/components/weather/ForecastPanel.tsx
src/components/weather/NextHourForecastPanel.tsx
src/components/weather/ObservationPanel.tsx
src/screens/WarningsScreen.tsx
src/screens/WeatherScreen.tsx

fix layout issues on android

---

src/components/weather/forecast/ForecastListColumn.tsx

remove minutes from ForecastHourList

---

README.md
android/app/build.gradle

update android documentation

---

src/components/warnings/WarningsPanel.tsx
src/components/warnings/WarningsWebViewPanel.tsx
src/components/weather/ForecastPanel.tsx
src/components/weather/ObservationPanel.tsx
src/components/weather/common/PanelHeader.tsx
src/screens/WeatherScreen.tsx

Updates the layout of the panels according to the design of the new layout.
Related issue: #322

Fix panels to take up full width of the screen

---

src/components/weather/forecast/DaySelectorList.tsx
src/components/weather/forecast/PrecipitationStrip.tsx

small changes to day selector styling

---

README.md

Add guidance for changing the port used by Metro server (and the application)

Add troubleshooting information to README

---

__tests__/config/testConfig.ts
src/config/types.ts
src/screens/OthersScreen.tsx

Enables configuring the social media links shown in OthersScreen in defaultConfig.ts.

Enable configuring social media links in defaultConfig

---

i18n/index.ts
src/screens/SettingsScreen.tsx

Hides language selection in settings screen if config only includes one language.
Related issue: #380

Hide language selection in settings if config only includes one language

---

src/components/map/layers/TimeseriesMarker.tsx

fix timeseries layer to show configured units

---

__tests__/config/testConfig.ts
__tests__/store/settings.test.ts
defaultConfig.ts.example
src/config/types.ts
src/navigators/TabNavigator.tsx
src/screens/SettingsScreen.tsx
src/store/settings/reducer.ts
src/store/settings/selectors.ts
src/store/settings/types.ts

Adds a configuration item for selecting the themes (light, dark) that the application UI supports and are available for users to select in the settings screen.

Enable configuring available themes in defaultConfig

---

src/components/warnings/cap/TextList.tsx
src/components/warnings/cap/WarningBlock.tsx
src/components/weather/sheets/WeatherInfoBottomSheet.tsx
src/network/CapWarningsApi.ts

Adds changes made to CAP view in JM fork to the main repository:
- filter out expired warnings
- show message when no warnings are active
- exclude day length -related parameters from WeatherInfoBottomSheet if day length is excluded in configuration
- add area description to UI

Update CAP view from fork

---

src/components/warnings/cap/WarningBlock.tsx

Resolves https://github.com/smartmet-jm/weather-app/issues/31.
Shows all areas for which the warnings in a group (currently by event code) apply.

List areas of all warnings in CAP warning group header

---

src/components/weather/charts/WindChart.tsx

https://github.com/smartmet-jm/weather-app/issues/47

Added useCardinals... -option to wind direction graph as well (JM-issue)

---

package.json
src/components/weather/forecast/ForecastByHourList.tsx
src/components/weather/sheets/WeatherInfoBottomSheet.tsx
src/config/types.ts

https://github.com/smartmet-jm/weather-app/issues/41

Added setting to remove midnight sun and polar night from UI (JM-issue)

---

src/components/warnings/cap/MapView.tsx

Resolves https://github.com/smartmet-jm/weather-app/issues/36.

Show unique warnings (severity + event) only in warnings type filters list

---

src/screens/AccessibilityScreen.tsx

resolves https://github.com/smartmet-jm/weather-app/issues/43

Added checks if there is any translations - if not -> don't add text

---

src/utils/map.ts

Issue-488 add Object handling

---

src/components/weather/forecast/ForecastByHourList.tsx

issue-459 use 06 value for the first day to dodge possible errors

---

android/app/src/main/java/fi/fmi/mobileweather/UpdateWidgetJobIntentService.java

URL change related to [FMI issue SOL-17164](https://jira.fmi.fi/browse/SOL-17164).

[SOL-17164] Change widget URL from m.fmi.fi to widget.weatherproof.fi

---

src/network/WeatherApi.ts
src/store/observation/reducer.ts
src/store/observation/selector.ts
src/store/observation/types.ts

Uses both stationtype and distance to sort observation stations.

issue-413: fix observation station order

---

defaultConfig.ts.example
i18n/en.json
i18n/fi.json
i18n/sv.json
src/components/weather/ObservationPanel.tsx
src/components/weather/charts/Chart.tsx
src/components/weather/charts/ChartDataRenderer.tsx
src/components/weather/charts/ChartYAxis.tsx
src/components/weather/charts/DailyChart.tsx
src/components/weather/charts/Legend.tsx
src/components/weather/charts/SnowDepth.tsx
src/components/weather/charts/settings.ts
src/components/weather/charts/types.ts
src/components/weather/common/ParameterSelector.tsx
src/components/weather/observation/DailyObservationRow.tsx
src/components/weather/observation/Latest.tsx
src/components/weather/observation/List.tsx
src/config/types.ts
src/network/WeatherApi.ts
src/store/observation/reducer.ts
src/store/observation/selector.ts
src/store/observation/types.ts
src/utils/chart.ts
src/utils/helpers.ts

Requires following additions to observation-block in `defaultConfig.ts`:
```
dailyProducers: ['observations_fmi'],
dailyParameters: [
'rrday',
'maximumTemperature',
'minimumTemperature',
'minimumGroundTemperature06',
'snowDepth06',
],
```

issue-307: add support for daily observations and parameters

---

i18n/en.json
i18n/fi.json
i18n/sv.json
src/components/weather/ObservationPanel.tsx
src/components/weather/charts/Chart.tsx
src/components/weather/charts/ChartYAxis.tsx
src/components/weather/charts/Legend.tsx
src/components/weather/charts/WeatherChart.tsx
src/components/weather/charts/settings.ts
src/components/weather/charts/types.ts
src/components/weather/observation/List.tsx
src/utils/chart.ts

- Added weather chart for observations that contains Temperature, DewPoint and Precipitation amount
- Removed temperature and precipitation charts from observations, however Temperature chart is used when current station doesn't have precipitation observations
- Added a bit tricky logic to keep temperature and precipitation axis in sync in new weather chart

issue-416: Added weather chart for observations

---

src/network/WeatherApi.ts

Probably #527 has solved the issue, but added extra checks for location before making API call.

issue-296: check that location is valid before api call

---

__tests__/store/location.test.ts
i18n/en.json
i18n/fi.json
i18n/sv.json
package.json
src/network/AutocompleteApi.ts
src/screens/SearchScreen.tsx
src/store/location/actions.ts
src/store/location/reducer.ts
src/store/location/selector.ts
src/store/location/types.ts
src/utils/axiosClient.ts
yarn.lock

Added loading indicator and cancelling previous autocomplete api calls to avoid multiple queries running same time.

issue-551: Improved location search

---

defaultConfig.ts.example
src/config/types.ts
src/utils/map.ts

If not defined default is 'png'

issue-598: Added support for tileFormat configuration option

---

i18n/en.json
i18n/fi.json
i18n/sv.json
src/screens/SettingsScreen.tsx

Bottom sheet is closed automatically after unit selection. Also added close button to unit selection bottom sheet.

issue-603: Improved unit selection

---

.github/workflows/latest.yml
android/fastlane/Fastfile
android/fastlane/README.md

Pipeline to build Android APK based on main branch on every push. The APK can be found from artifacts section after action is run and downloaded to own computer, unzipped and then installed with `adb install latest.apk`

issue-635: The latest build from main branch

---

src/screens/OnboardingScreen.tsx
src/screens/SetupScreen.tsx

Unfortunately react-native-svg doesn't seem to support testID, so could not add testID to Icon-component.

issue-644: Added testIDs to OnboardingScreen and SetupScreen

---

e2e/warnings.test.ts
src/screens/WarningsScreen.tsx

issue-611: Hide warning panel for foreign locations

---

ios/MobileWeather.xcodeproj/project.pbxproj
ios/Widget/Assets.xcassets/ForecastRowBackground.colorset/Contents.json
ios/Widget/Assets.xcassets/TextColor.colorset/Contents.json
ios/Widget/Assets.xcassets/WidgetBackground.colorset/Contents.json
ios/Widget/Assets.xcassets/WindArrows/E.imageset/Contents.json
ios/Widget/Assets.xcassets/WindArrows/E.imageset/E-dark.svg
ios/Widget/Assets.xcassets/WindArrows/N.imageset/Contents.json
ios/Widget/Assets.xcassets/WindArrows/N.imageset/N-dark.svg
ios/Widget/Assets.xcassets/WindArrows/NE.imageset/Contents.json
ios/Widget/Assets.xcassets/WindArrows/NE.imageset/NE-dark.svg
ios/Widget/Assets.xcassets/WindArrows/NW.imageset/Contents.json
ios/Widget/Assets.xcassets/WindArrows/NW.imageset/NW-dark.svg
ios/Widget/Assets.xcassets/WindArrows/S.imageset/Contents.json
ios/Widget/Assets.xcassets/WindArrows/S.imageset/S-dark.svg
ios/Widget/Assets.xcassets/WindArrows/SE.imageset/Contents.json
ios/Widget/Assets.xcassets/WindArrows/SE.imageset/SE-dark.svg
ios/Widget/Assets.xcassets/WindArrows/SW.imageset/Contents.json
ios/Widget/Assets.xcassets/WindArrows/SW.imageset/SW-dark.svg
ios/Widget/Assets.xcassets/WindArrows/W.imageset/Contents.json
ios/Widget/Assets.xcassets/WindArrows/W.imageset/W-dark.svg
ios/Widget/Assets.xcassets/clock.imageset/Contents.json
ios/Widget/Assets.xcassets/symbol.imageset/Contents.json
ios/Widget/Assets.xcassets/temperature.imageset/Contents.json
ios/Widget/ForecastWidget.swift
ios/Widget/WarningsTodayWidget.swift
ios/Widget/defaults.swift
ios/Widget/types.swift
ios/Widget/utils.swift
ios/Widget/views/forecast/LargeNextHoursForecast.swift
ios/Widget/views/forecast/NextHourForecastExtraRow.swift

- Widgets use theme from settings
- Added saving and restoring entries from UserDefaults to forecast widget
- Uses widget settings in UserDefaults cache key so that widget settings doesn't change when old entries are used

issue-658: iOS widget themes

---

.github/workflows/latest.yml
.github/workflows/main.yml

Needs that WIDGETCONFIG is added to secrets same way like existing DEFAULTCONFIG

issue-706: Added widgetConfig.json to pipelines

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/fi/fmi/mobileweather/BaseWidgetConfigurationActivity.java
src/navigators/TabNavigator.tsx

- App can be opened with `fmiweather://` url and for search screen there is more specific `fmiweather://search` url
- Widget configuration uses new url to open location search view
- Improved widget configuration to refresh location options when resuming so that new favorites are visible when coming back from location search view.

issue-703: Added fmiweather://search url handler

---

android/app/src/main/res/layout/horizontal_forecast_widget_layout.xml

Changed from three column layout to two column layout that gives more space for location name.

issue-739: Improved small widget horizontal layout

---

android/app/src/main/java/fi/fmi/mobileweather/BaseWidgetProvider.java
android/app/src/main/java/fi/fmi/mobileweather/LargeForecastWidgetProvider.java
android/app/src/main/java/fi/fmi/mobileweather/MaxForecastWidgetProvider.java
android/app/src/main/res/layout/forecast_timestep.xml
android/app/src/main/res/layout/large_forecast_widget_layout.xml
android/app/src/main/res/layout/max_forecast_widget_layout.xml
android/app/src/main/res/xml-v31/large_widget_provider_info.xml
android/app/src/main/res/xml-v31/max_widget_provider_info.xml

Mostly improvements for 5 column homescreens. Theme related issues has been fixed in other tickets.

issue-742: Android widget layout fixes

---

src/network/WeatherApi.ts
src/store/forecast/types.ts
src/utils/helpers.ts

Uses timeseries localtime-parameter to determine 15:00 localtime more reliably.

issue-721: Improved getIndexForDaySmartSymbol() function

---

ios/Widget/ForecastWidget.swift
ios/Widget/Localizable.xcstrings
ios/Widget/WarningsTodayWidget.swift
ios/Widget/types.swift
ios/Widget/views/forecast/ForecastColumn.swift
ios/Widget/views/forecast/LargeNextHoursForecast.swift
ios/Widget/views/warnings/WarningsErrorView.swift

Fixed missing translation and some other bugs:
- Fixed medium forecast to show times correctly for foreign locations (timezone was missing)
- Fixed widgets to show country for foreign locations
- Added 2px more width to large forecast columns to have more space to show time

issue-773: Translation and bug fixes

---

ios/Podfile.lock
package.json
src/components/warnings/cap/CapSeverityBar.tsx
src/components/warnings/cap/MapView.tsx
src/components/warnings/cap/TextList.tsx
src/components/warnings/cap/WarningBlock.tsx
src/components/warnings/cap/WarningTypeFiltersList.tsx
src/network/CapWarningsApi.ts
src/store/warnings/types.ts
src/utils/helpers.ts
src/utils/map.ts
yarn.lock

Also updated fast-xml-parser to latest 4.x version (was 3.21.1). Because of that also had to change GetCapabilities XML parsing a bit.

issue-760: CAP parser improvements to handle Meteoalarm feeds

---

android/app/src/main/res/xml/network_security_config.xml
ios/MobileWeather/Info.plist
src/network/CapWarningsApi.ts

Also allowed http-connections to smartmet-demo server

issue-761: CAP parser bug fix

---

android/app/src/main/java/fi/fmi/mobileweather/BaseWidgetProvider.java
android/app/src/main/res/layout/horizontal_forecast_widget_layout.xml
android/app/src/main/res/layout/small_forecast_widget_layout.xml

°C -> ° and small margin change to give more space for content

issue-841: Small Android widget layout improvements

---

src/components/warnings/WarningIconsPanel.tsx
src/components/weather/ForecastPanelWithVerticalLayout.tsx
src/components/weather/NextHourForecastPanelWithWeatherBackground.tsx
src/components/weather/NextHoursForecast.tsx
src/components/weather/ObservationPanel.tsx
src/components/weather/common/ParameterSelector.tsx
src/components/weather/sheets/ObservationStationListBottomSheet.tsx
src/components/weather/sheets/ParamsBottomSheet.tsx

Also added fading to background color to be done in the app and improved safe area margins/paddings.

issue-860: Separate weather backgrounds for phones/tables

---

src/components/weather/charts/Legend.tsx

Could not repeat the issue, but 20px more space should fix the issue.

issue-865: Added more space for cloud cover texts in legend

---

src/components/weather/NextHourForecastPanelWithWeatherBackground.tsx

- Updated some background images
- Added shadows to text
- Allows to define white or black text to specific background to override default color

issue-854: Impoved text readability with weather backgrounds

---

src/components/weather/NextHourForecastPanelWithWeatherBackground.tsx
src/components/weather/forecast/Vertical10DaysForecast.tsx

Also removed Huomenna/Tomorrow text, because it requires much more space. Replaced with weekday abbreviation.

issue-859: Text and spacing adjustments

---

src/components/weather/MeteorologistSnapshot.tsx
src/config/types.ts
src/navigators/types.ts
src/network/MeteorologistSnapshotApi.ts
src/screens/WeatherScreen.tsx
src/store/index.ts
src/store/meteorologist/actions.ts
src/store/meteorologist/reducer.ts
src/store/meteorologist/selector.ts
src/store/meteorologist/types.ts
src/store/types.ts

Requires configuration
```
meteorologist: {
url: [url],
updateInterval: 10,
}
```
under weather-section. Texts are hardcoded, because the feature is available only in finnish.

issue-832: Implemented meteorologist snapshot

---

src/components/weather/NextHourForecastPanelWithWeatherBackground.tsx

- Location name bold fix for Android
- Location name uses only one line
- Max width for the row that contains wind information, UV, precipitation amount and feels like

issue-852: Some fixes for location name and next hour forecast

---

src/components/warnings/WarningsPanel.tsx

Wrong state variable was used to check should panel be shown or not.

issue-921: Fixed local warnings loading issue and added skeleton loading

---

src/components/weather/forecast/Vertical10DaysForecast.tsx

When the app comes from background to active the app checks should the modal be closed if there is forecast anymore for the selected day.

issue-919: Added logic to close modal automatically

---

i18n/en.json
i18n/fi.json
i18n/sv.json
src/components/weather/forecast/Vertical10DaysForecast.tsx

Also added "Temperature" and "Wind speed" texts to accessibility labels to make parameter more clear.

issue-945: Fixed incorrect wind speed accessibility label

---

package.json
src/components/warnings/WarningsWebViewPanel.tsx
src/config/ConfigProvider.tsx
src/config/DynamicConfig.ts
yarn.lock

Also
- Changed to use mmkv with dynamicConfig
- Added whitelist for webview hostnames

issue-971: Added blacklist for dynamicConfig features

---

src/components/weather/SunAndMoonPanel.tsx
src/screens/WeatherScreen.tsx

Moved day length and moon phase boxes after meteorologist text in the UI.

issue-986: Moved day length and moon phase boxes

---

i18n/en.json
i18n/fi.json
i18n/sv.json
src/components/warnings/WarningIconsPanel.tsx
src/components/warnings/WarningsPanel.tsx
src/store/warnings/selectors.ts

Also fixed bug in warning severity sorting that caused incorrect warning to be displayed as main warning in WarningsIconPanel in some cases.

issue-1029: Implemented error handling for local warnings

---

i18n/en.json
i18n/fi.json
i18n/sv.json
src/screens/SettingsScreen.tsx

Fixed screen reader unit pronunciations, added knots (kn) to translation files and fixed a small typo in sv.json.

1025 unit pronunciations

---

i18n/en.json
i18n/fi.json
i18n/sv.json
src/components/weather/forecast/ForecastListColumn.tsx
src/utils/helpers.ts

PoP parameter is rounded to nearest ten or shown as <10 or >90.

issue-1045: Show precipitation probability with less accuracy

---

src/components/common/ErrorComponent.tsx
src/navigators/TabNavigator.tsx

The issue was caused that `ErrorComponent` received undefined route initially and it didn't update automatically until tab was changed. Implemented route detection different and more reliable way.

issue-1074: Improved route handling for ErrorComponent

---

src/components/weather/forecast/ModalForecast.tsx
src/components/weather/forecast/Vertical10DaysForecast.tsx
src/components/weather/forecast/constants.ts

Adjusted modal layout to work better with small screens. Scrolling is applied now when 10 weather parameters or more is selected.

issue-1053: Adjusted modal layout for small screens

---

src/screens/SearchScreen.tsx
src/store/forecast/actions.ts

Also:
- Adding favorite from search results doesn't clear search input and results anymore
- Fixed data loading issue for foreign locations

issue-1065: Implemented remove favourite for search results

---

ios/Podfile.lock
src/components/map/layers/TimeseriesMarker.tsx
src/screens/MapScreen.tsx

Should work and iOS and android.
**How to test**
- open app and then go to map page
- select timeseries wms
- smaller signs should appear to the map with wx symbol + temperature
- clicking a sign should make it larger and show location name and other values
fixes #1083

Issue 1083 fix timeseries wms android
