fmidev/weather-app

src/components/map/sheets/MapLayersBottomSheet.tsx
Apparently `TouchableOpacity` was autoimported from `react-native-gesture-handler` instead of `react-native` which managed to work on iOS as expected but not on android.
Closes #88
=> fix wrong import on MapLayersBottomSheet

src/navigators/TabNavigator.tsx
Negative bottom margin broke tab bar on some ios devices. Remove to fix.
=> remove tab bar negative bottom margin on ios

src/components/weather/NextHourForecastPanel.tsx
Updates the UI layout of the next hour forecast in accordance with the design at https://app.zeplin.io/project/60c1a26998847f8bb7e536cb/screen/62989b349a7b696f998e714d.
Related issue: #320
=> Update UI layout of next hour forecast

src/components/map/layers/WMSOverlay.tsx, src/utils/map.ts
Adds support for WMS layers with only forecast or observation defined.
Partial mock config:
```
map: {
updateInterval: 5,
sources: {
source: http://source.example,
},
layers: [
{
id: 1,
type: 'WMS',
name: { en: 'test', fi: 'test', sv: 'test' },
sources: [
{
source: 'source',
layer: 'some:wms:layer',
type: 'forecast',
},
],
times: {
timeStep: 180,
forecast: 4,
},
},
],
},
```
Closes #335
=> implement forecast or observation only wms layer

src/components/weather/charts/Chart.tsx
The issue in #317 is that the dayIndex is not kept up-to-date, leading conditions in if-statements to evaluate to incorrect values and thus skipping scrolling when it should not be skipped.
This PR keeps the scrollIndex up-to-date, which in turn keeps the dayIndex up-to-date.
=> Fix interaction problems between day selector and chart

i18n/fi.json, src/utils/helpers.ts, src/utils/units.ts
Enables observation values to be rounded to unit precision (by default) and to other precisions when an alternate precision is specified.
Addresses issue #355.
=> Fix displayed precision of temperature observations

src/components/map/ui/TimeSlider.tsx, src/components/warnings/WarningsPanel.tsx, src/components/weather/charts/Chart.tsx, src/components/weather/charts/ChartDataRenderer.tsx, src/components/weather/forecast/DaySelectorList.tsx, src/components/weather/observation/Latest.tsx, src/utils/chart.ts
Fixes weekday abbreviations to use 3 characters instead of 2 when English is chosen as the application's language,
Related issue: #352
=> Fix English weekday abbreviations

src/navigators/TabNavigator.tsx, src/navigators/WarningsTabIcon.tsx
Makes warning information available to screen readers in TabNavigator.
Related issue: #361
=> Make warning information available to screen readers in TabNavigator

i18n/en.json, i18n/fi.json, i18n/sv.json, src/components/weather/forecast/ForecastByHourList.tsx, src/components/weather/forecast/ForecastListColumn.tsx, src/components/weather/forecast/ForecastListHeaderColumn.tsx, src/components/weather/sheets/ParamsBottomSheet.tsx, src/store/forecast/constants.ts, src/store/forecast/selectors.ts
Enables toggling the visibility of day length in ForecastByHourList.
Related issue: #359
=> Enable selecting day length as shown/hidden in ForecastByHourList

src/screens/MapScreen.tsx
Reads map default location from config and uses it if no location has been selected.
Related issue: #372.
=> Use location from config as default location for map

src/navigators/TabNavigator.tsx
Hides warnings tab in TabNavigator if warnings have been disabled in the configuration  (`enabled: false` in warnings section of config).
Resolves issue #384.
=> Hide warnings tab if warnings have been disabled in config

__tests__/config/testConfig.ts, __tests__/store/settings.test.ts, defaultConfig.ts.example, src/config/types.ts, src/store/settings/reducer.ts, src/store/settings/selectors.ts, src/store/settings/types.ts
Adds a property `clockType` in the config to enable setting the default clock type.
Resolves issue #387.
=> Enable setting default clock type in config

src/components/warnings/DayDetails.tsx, src/components/warnings/WarningsPanel.tsx
Fixes English date formats and 12-hour time formats in warnings screen (WarningsPanel and DayDetails).
Resolves issue #397.
=> Fix date and time formats in WarningsPanel and DayDetails

src/components/weather/forecast/DaySelectorList.tsx
Improves the accessibility of the day selectors in the forecast panel by announcing whether or not the date read by a screen reader has been selected.
=> Announce selected day in forecast panel

src/utils/helpers.ts
Fix logic for choosing the smart symbol shown in day selector. The smart symbol should be chosen for the forecast at 14:00/2.00 PM if available.
=> Fix smart symbol selection logic in DaySelector

src/components/weather/NextHourForecastPanel.tsx
Show "-" instead of null when the UV value received from the server is null.
=> Show dash if UV is null or undefined

src/components/weather/ObservationPanel.tsx, src/components/weather/observation/Latest.tsx
Resolves #414, #415.
Removes observation parameter selector buttons for parameters that are not measured by an observation station (i.e. no data exists for a given parameter).
=> Hide observation parameter selectors for parameters with no data

__tests__/config/testConfig.ts, defaultConfig.ts.example, src/config/types.ts, src/navigators/TabNavigator.tsx
Resolves #445.
Enables configuring onboarding wizard to be skipped and therefore not shown to the user.
=> Enable configuring use of onboarding wizard

src/components/weather/forecast/ForecastByHourList.tsx, src/components/weather/sheets/ParamsBottomSheet.tsx, src/config/types.ts
Introduces a config option for excluding day length from the parameters shown in the forecast view and parameter selection sheet.
=> Make visibility of day length configurable

src/components/warnings/cap/MapView.tsx, src/components/warnings/cap/WarningBlock.tsx, src/network/CapWarningsApi.ts, src/store/warnings/actions.ts, src/store/warnings/types.ts, src/utils/helpers.ts
Relates to issue #433.
Changes:
- use `effective` field instead of `onset` field in CAP message as the start time of the warning
- change the "Updated" date shown in UI to be the date reported in the CAP message
- add logic for disregarding irrelevant messages and handling messages of types "Update", "Cancel"
=> Cap improvements

src/components/warnings/cap/MapView.tsx
Fixes CAP map view to only show one filter button per event-severity combination. Currently a filter button is displayed for all warnings, which sometimes results in many identical buttons being rendered.
=> Only show one filter button per event/severity combination

src/components/warnings/cap/CapWarningsView.tsx, src/config/types.ts
Enables configuring the visibility of current location in the CAP warnings text list view title.
Resolves https://github.com/smartmet-jm/weather-app/issues/32.
=> Make showing location in CAP text list configurable

ios/MobileWeather.xcodeproj/project.pbxproj, ios/Podfile.lock, src/components/weather/NextHourForecastPanel.tsx, src/components/weather/forecast/ForecastListColumn.tsx, src/components/weather/observation/List.tsx, src/config/types.ts, src/utils/helpers.ts
Added cardinal support (direction is rounded to N, NE, E, ... directions) to settings. Works in following UI elements:
- next hour's forecast -panel
- hourly forecast table
- observation's wind -list -tab's table
defaultConfig.ts can have weather.useCardinalsForWindDirection -setting. Using degrees by default.
=> Jamaica issue 10 - setting for using cardinals instead of degrees on wind direction

src/components/map/ui/SliderStep.tsx, src/components/map/ui/TimeSlider.tsx
Resolves issue 484.
Widens the steps in `TimeSlider` so that the time steps fit in the layout also in 12-hour format.
=> Fix layout issue in map time slider when 12-hour clock is in use

src/utils/axiosClient.ts
Tested the app with simulated 2G connection speeds. 10s timeout was too short to load forecasts and observations, 20s timeout seems to work much better.
Other idea was to add retries if API queries fail, but didn't implement that yet, because it might cause too many connections to pile up on server if we run 20s + 20s queries for large number of users. At least it would need some discussions with server people.
Also didn't add timeout to configuration, because that caused cyclic dependency with imports and probably there is no need to change default timeout.
=> issue-534: increased axiosClient default timeout

package.json, src/network/AutocompleteApi.ts, src/network/WeatherApi.ts, src/utils/axiosClient.ts, yarn.lock
The library didn't work well with axios CancelToken, so had to convert CancelToken usage to AbortController. CancelToken is deprecated anyway, so the change is better for the future anyway.
Also starttime was removed from forecast queries to keep querystring same and cacheable.
=> issue-582: Use axios-cache-interceptor to cache timeseries queries

src/store/observation/reducer.ts
Typical javascript issue that the same array was mutated multiple times and that caused irregular order for observations. The root cause was that axios-cache-interceptor was added previously and the library returns same object from memory cache if it exists. The data returned by axios-cache-interceptor was mutated in formatData-method, often multiple times.
Also tried to fix issue by adding `cloneData` option for axios-cache-interceptor, but that didn't work
https://axios-cache-interceptor.js.org/guide/storages
=> issue-588: Fix for irregular order in observation list

android/app/src/main/java/fi/fmi/mobileweather/MainActivity.kt
Some code was lost in Kotlin conversion that caused splash screen not showing and occasional crashes in some devices/Android versions.
=> issue-605: Restored code that was lost in java -> kotlin conversion

defaultConfig.ts.example, ios/MobileWeather.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json, src/components/map/layers/MemoizedWMSTile.tsx, src/config/types.ts, src/screens/MapScreen.tsx, src/utils/map.ts, yarn.lock
- Updated react-native-maps to latest version
- tileSize 256 is default if not configured
- tileSize can be configured by platform, because seems that 256 is the best for Android and 1024 for iOS (smaller sizes cause flickering for some reason)
=> issue-593: Platform specific tileSize configuration

ios/Podfile.lock, package.json, src/components/warnings/WarningsWebViewPanel.tsx, yarn.lock
JS-code
```
document.getElementById('fmi-warnings').__vue__.update();
```
doesn't work with current Smartmet Alert client. Android webview and earlier iOS versions silently ignored javascript error, but in iOS18 this caused injectScript-error.
Smartmet Alert client updates warnings when warning view tab is activated or when app comes active from background state, so it should update often enough so that same warnings are displayed in `WarningsPanel` and on the map.
Also updated react-native-webview to latest version, because there seemed to be some iOS fixes.
=> issue-608: Removed javascript-code that caused injectScript error in iOS 18

src/store/forecast/selectors.ts, src/utils/helpers.ts
14:00 local time was used before the change. There was also other issue
The code
```
const index = dayArray.findIndex((d) => {
const dateObj = new Date(d.epochtime * 1000);
const hours = dateObj.getHours();
return hours === 14;
});
```
used device local time and didn't work for foreign locations. Removed code, because it returned random indexes for foreign locations. The zero index is returned instead, because it is closest to 15:00 if that time is passed already.
=> issue-601: Use 15:00 local time for daily weather symbol if available

ios/Podfile.lock, package.json, src/utils/helpers.ts, yarn.lock
Changed react-native-geolocation-service to react-native-geolocation, because longitude 0 on iOS is known issue in react-native-geolocation-service and the library is not developed actively.
=> issue-609: Use react-native-geolocation

src/components/warnings/WarningsWebViewPanel.tsx, src/components/weather/ForecastPanel.tsx, src/components/weather/NextHourForecastPanel.tsx, src/components/weather/forecast/ForecastByHourList.tsx, src/config/ConfigProvider.tsx, src/screens/WarningsScreen.tsx, src/screens/WeatherScreen.tsx, src/store/forecast/selectors.ts
Modified `ConfigProvider` by adding `reloadInterval` (1 minute). Therefore components that are using existing `ReloaderContext` run their own own logic for updates every minute if the app is active.
The special case is that forecast views are refreshed when the hour changes.
Didn't implement layer specific logic for the map view, because felt that it would add too much complexity for little benefit. Most use cases (99.9% or something) still use old logic to check updates when the app becomes active and the new interval based logic is just for developers and users running the app in active always mode (the iPad on the wall etc.)
Also didn't add any new configuration options for `defaultConfig`, existing update intervals are still used.
=> issue-612: Update data by interval

src/config/ConfigProvider.tsx, src/config/DynamicConfig.ts, src/utils/async_storage.ts
Optimized config loading by saving dynamiconfig locally and updating it only when etag header or app version changes. Amazon S3 calculates etag automatically for every document/file.
=> issue-620: Store dynamiconfig locally and use etag for updating it

src/components/weather/sheets/WeatherInfoBottomSheet.tsx
`windSpeedMap` was missing values for knots unit that caused crash when `WeatherInfoBottomSheet` was opened. Added values based on `m/s` values.
=> issue-625: Added missing windSpeedMap values for knots unit

mockserver/data/config/config.json
localhost doesn't work well with Android emulator, because localhost is emulator itself. Changed DynamicConfig file to use 10.0.2.2 instead.
https://stackoverflow.com/questions/9808560/why-do-we-use-10-0-2-2-to-connect-to-local-web-server-instead-of-using-computer
=> issue-690: Use 10.0.2.2 instead of localhost with mockserver

.gitignore, android/app/src/main/assets/widgetConfig.json
Changed Android widgetConfig.json to symbolic link, so that it is enough to update one widgetConfig.json in project root.
=> issue-706: Android widgetConfig symbolic link

mockserver/modifiers.mjs, src/components/common/ErrorComponent.tsx, src/components/weather/forecast/DaySelectorList.tsx, src/store/forecast/selectors.ts
- Checks if all forecast timesteps have `null` temperature value and displays error
- Improved error display that errors are displayed only on tabs that they concern. Also allows more than one retry now.
- Added `localtime` to mock server forecast data, because current version needs it
=> issue-791: Check for invalid forecast data and error display improvements

.github/workflows/latest.yml
Creates releases to https://github.com/fmidev/weather-app/releases/tag/latest and the APK has static url that can be used in tests.
=> issue-794: Static release url for Android APK

src/components/weather/observation/Latest.tsx
Seems that on winter time daily snow depth observations are part of normal observations and therefore larger amount of normal or instant observations must be allowed. 3 seems to be working for the stations mentioned in the ticket.
=> issue-694: Small fix for only daily observations notification

src/components/weather/NextHourForecastPanelWithWeatherBackground.tsx, src/components/weather/charts/TemperatureChart.tsx, src/config/types.ts, src/network/WeatherApi.ts, src/screens/WeatherScreen.tsx, src/store/forecast/types.ts, src/store/observation/reducer.ts, src/store/observation/selector.ts, src/store/observation/types.ts, src/utils/geoMagneticStations.ts
Requires following changes to defaultConfig:
Add totalCloudCover to forecast-parameters
```
forecast: {
updateInterval: 30,
timePeriod: 'data',
data: [
{
producer: 'default',
parameters: [
'temperature',
'feelsLike',
'dewPoint',
'smartSymbol',
'windDirection',
'windSpeedMS',
'pop',
'hourlymaximumgust',
'relativeHumidity',
'pressure',
'precipitation1h',
'windCompass8',
'totalCloudCover',
],
},
{ producer: 'uv', parameters: ['uvCumulated'] },
],
```
Add geoMagneticObservations to observation-section
```
geoMagneticObservations: {
enabled: true,
producer: 'magnetic_disturbance_observations',
countryCodes: ['FI', 'EE'],
},
```
=> issue-820: Added logic for aurora borealis backgrounds

src/config/types.ts, src/screens/OnboardingScreen.tsx, src/screens/SetupScreen.tsx
Allows to specify language specific provider logos in weather-app-assets. Also needs configuration option `languageSpecificLogo: true` to OnboardingWizard configuration. If these are not specified uses default images like before.
=> issue-877: Added support for language specific provider logos

src/components/weather/forecast/ModalContent.tsx, src/components/weather/forecast/ModalForecast.tsx, src/components/weather/forecast/Vertical10DaysForecast.tsx
- Improved modal close by swipe. It is now possible to swipe to close from anywhere in the modal, not just from header. Only when there are lot of forecast parameters or little vertical space (landscape displays) then vertical scrollview prevents swipe to close from scrollview content.
- Hides time selection buttons from tablets and landscape displays giving more space for weather content
- Backward and forward buttons go to either start or end of the day forecast, not to random position anymore
=> issue-867: Modal improvements

i18n/en.json, i18n/fi.json, i18n/sv.json, src/components/weather/NextHourForecastPanelWithWeatherBackground.tsx, src/utils/helpers.ts
How to test:
- Open weather page and search a cold area (currently e.g. Grytviken, GS)
- Enable screen reader
- Make sure negative degrees on the forecast panel are pronounced as negative (e.g. "minus two degrees celsius")
=> Fixed weather bar screen reader pronunciation for negative temperatures

src/components/weather/forecast/ModalForecast.tsx
Seems that first timesteps of daily data contain suntimes for previous day, so use the last timestep of daily data.
=> issue-1046: Fixed sunrise and sunset times

src/utils/units.ts
...and because of that conversion to other wind units was not applied.
=> issue-1044: Wind gust was missing from unit definitions

i18n/en.json, i18n/fi.json, i18n/sv.json, src/config/DynamicConfig.ts, src/config/types.ts, src/navigators/TabNavigator.tsx, src/screens/SetupScreen.tsx, src/store/navigation/reducer.ts, src/store/navigation/selectors.ts, src/store/navigation/types.ts
Requires new setting under onboardingWizard, for example
```
onboardingWizard: {
enabled: true,
termsOfUseChanged: true,
},
```
`onboardingWizard` is now blaclisted and can't be changed with DynamicConfig to avoid issues with this feature.
=> issue-959: Implemented Terms of Use display & accept when changes

src/network/WeatherApi.ts, src/store/forecast/actions.ts
If forecast data is 24 hours or more old then try to retry with different who-parameter and without If-Modified-Since header (eTag).
=> issue-1079: Implemented retry-logic for forecasts
